### ISSUE TITLE
实验复现结果与论文中不一致

### ISSUE THREAD

**Issue by liaoke123** [zshicode/MambaLithium#1]
您好，我按照README.md的指示，进行了python main.py --task RUL  和   python main.py --task SOH的操作。结果分别如下：

MSE RMSE MAE R2
0.0000, 0.0018, 0.0013, 0.9981

MSE RMSE MAE R2
259.9479 16.1229 13.1153 0.9990
与论文中的结果不一致，是我理解错了吗，还请解惑下，谢谢！
SOH的结果：
![QQ截图20240411195737](https://github.com/zshicode/MambaLithium/assets/55182012/cdfecd85-199f-4914-a0e1-1d043877c4f6)
RUL的结果：
![QQ截图20240411195704](https://github.com/zshicode/MambaLithium/assets/55182012/8e4fb277-abe6-409c-8a14-56a8649ea4c9)

**Comment by zshicode** [comment]
由于神经网络的训练有一定的随机性，所以在不同的电脑、不同的库的版本之下进行训练，结果会有一定的波动。从你训练的结果来看，仍然可以说明MambaLithium的优秀性能，可能也还有通过调整参数达到更好的性能的空间。
